[package]
    edition           = "2021"
    name              = "models"
    version.workspace = true

[dependencies]
    anyhow.workspace     = true
    common_utils         = { path = "../common" }
    serde.workspace      = true
    serde_json.workspace = true
    serde_repr.workspace = true
