[formatting]
    align_entries = true

    indent_entries = true
    indent_string  = "    "
    indent_tables  = true

    reorder_arrays        = true
    reorder_inline_tables = true
    reorder_keys          = true

[[rule]]
    include = ["Cargo.toml", "cargo.toml"]

    [rule.schema]
        path = "https://json.schemastore.org/cargo.json"
